M48
; DRILL file {KiCad 7.0.6} date Wed Oct 18 11:42:17 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-18T11:42:17+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0469
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1063
%
G90
G05
T1
X3.9809Y-3.2192
X3.9809Y-3.6492
T2
X4.5232Y-3.1447
X4.5232Y-3.2447
T3
X4.5Y-3.6
T0
M30
